vich_uploader:
    db_driver: orm

    mappings:
        conferences_images:
            uri_prefix: '%conferences_images%'
            # uri_prefix: /uploads/conferences/images
            upload_destination: '%kernel.project_dir%/public%conferences_images%'
            # upload_destination: '%kernel.project_dir%/public/uploads/conferences/images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: false
            delete_on_remove: false
