version: '3.8'

services:
  ################
  # DATABASE
  ################
  database:
    container_name: database
    image: mysql:${MYSQL_VERSION}
    command: [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    restart: always
    ports:
      - '4306:3306'
    volumes:
      - ./config/mysql:/var/lib/mysql
    networks:
      - kodo
  ################
  # PHP CONTAINER
  ################
  php:
    container_name: php
    build:
      context: ./config/php
      args:
        PHP_VERSION: ${PHP_VERSION}
        GIT_USER_NAME: ${GIT_USER_NAME}
        GIT_USER_EMAIL: ${GIT_USER_EMAIL}
        COMPOSER_VERSION: ${COMPOSER_VERSION}
        APP_DIR_NAME: ${APP_DIR_NAME}
    ports:
      - '9000:9000'
    volumes:
      - ./www:/var/www/${APP_DIR_NAME}
      - ./config/php/logs/:/var/log/
    depends_on:
      - database
    networks:
      - kodo
  ################
  # SERVER WEB
  ################
  nginx:
    container_name: nginx
    image: nginx:${NGINX_VERSION}
    ports:
      - '8080:80'
    environment:
      - APP_DIRNAME=${APP_DIR_NAME}
      - NGINX_HOST=${NGINX_HOST}
    volumes:
      - ./www:/var/www/${APP_DIR_NAME}
      - ./config/nginx/site.conf:/etc/nginx/conf.d/default.conf
      - ./config/nginx/logs/:/var/log/nginx
    depends_on:
      - php
      - database
    networks:
      - kodo
  ################
  # TOOLS
  ################
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - '8091:80'
    links:
      - database:database
    networks:
      - kodo

networks:
  kodo:
